{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 367,
   "metadata": {},
   "outputs": [],
   "source": [
    "# default_exp metaflow"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 368,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "import asyncio\n",
    "import multiprocessing\n",
    "import os\n",
    "import subprocess\n",
    "from pathlib import Path, PosixPath\n",
    "from typing import Any, Dict, Iterable\n",
    "from itertools import product\n",
    "\n",
    "from fastcore.script import call_parse\n",
    "from nbdev.export import Config, find_default_export, nbglob, read_nb\n",
    "from sciflow.data_handler import extract_param_meta\n",
    "from sciflow.params import params_as_dict\n",
    "from sciflow.parse_module import FuncDetails, extract_steps"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Sciflow Notebook to MetaFlow Flow\n",
    "\n",
    "> Converts from a `sciflow` format notebook to a `metaflow` flow. \n",
    "\n",
    "Supported features:\n",
    "\n",
    "* Linear/sequential DAGs\n",
    "* Simple `Parameters`"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 369,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The autoreload extension is already loaded. To reload it, use:\n",
      "  %reload_ext autoreload\n"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 370,
   "metadata": {},
   "outputs": [],
   "source": [
    "nb_path = Path(os.path.join(\"test\", \"test_export.ipynb\"))\n",
    "nb = read_nb(nb_path)\n",
    "module_name = find_default_export(nb[\"cells\"]).replace(\".\", \"/\")\n",
    "test_module = os.path.join(Config().path(\"lib_path\"), f\"{module_name}.py\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 371,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def titleize(name):\n",
    "    return name.title().replace(\"_\", \"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 372,
   "metadata": {},
   "outputs": [],
   "source": [
    "assert titleize(\"snake_case\") == \"SnakeCase\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 373,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def rename_steps_for_metaflow(steps):\n",
    "    for i, step in enumerate(steps):\n",
    "        if i == 0:\n",
    "            step.name = \"start\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 374,
   "metadata": {},
   "outputs": [],
   "source": [
    "steps = extract_steps(test_module)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 375,
   "metadata": {},
   "outputs": [],
   "source": [
    "no_steps = extract_steps(os.path.join(Config().path(\"lib_path\"), f\"_nbdev.py\"))\n",
    "assert len(no_steps) == 0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 376,
   "metadata": {},
   "outputs": [],
   "source": [
    "assert [\"first\", \"preprocess\", \"train\", \"last\"] == [step.name for step in steps]\n",
    "rename_steps_for_metaflow(steps)\n",
    "assert [\"start\", \"preprocess\", \"train\", \"last\"] == [step.name for step in steps]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 377,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def indent_multiline(multiline_text, indent=1):\n",
    "    lines = multiline_text.strip().split(\"\\n\")\n",
    "    spaces = \"\".join([\"    \" for _ in range(indent)])\n",
    "    for i in range(len(lines)):\n",
    "        prefix = spaces if i > 0 else spaces + '\"\"\"'\n",
    "        lines[i] = prefix + lines[i]\n",
    "    return \"\\n\".join(lines) + '\"\"\"'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 378,
   "metadata": {},
   "outputs": [],
   "source": [
    "text = \"\"\"\n",
    "Some text\n",
    ":param param: text\n",
    "\"\"\"\n",
    "assert '    \"\"\"Some text\\n    :param param: text\"\"\"' == indent_multiline(text)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 379,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Test Returns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 380,
   "metadata": {},
   "outputs": [],
   "source": [
    "nb_path = Path(os.path.join(\"test\", \"test_clustering.ipynb\"))\n",
    "nb = read_nb(nb_path)\n",
    "module_name = find_default_export(nb[\"cells\"]).replace(\".\", \"/\")\n",
    "test_module = os.path.join(Config().path(\"lib_path\"), f\"{module_name}.py\")\n",
    "steps = extract_steps(test_module)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 381,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def nb_to_metaflow(nb_path: Path, flow_path: Path, silent=True, track_experiment=True):\n",
    "    nb = read_nb(nb_path)\n",
    "    lib_name = Config().lib_name\n",
    "    module_name = find_default_export(nb[\"cells\"])\n",
    "    if not module_name:\n",
    "        return\n",
    "    module_name = module_name\n",
    "    path_sep_module_name = module_name.replace(\".\", \"/\")\n",
    "    nb_name = os.path.basename(nb_path)\n",
    "    exported_module = os.path.join(\n",
    "        Config().path(\"lib_path\"), f\"{path_sep_module_name}.py\"\n",
    "    )\n",
    "    steps = extract_steps(exported_module)\n",
    "    if len(steps) == 0:\n",
    "        return\n",
    "    orig_step_names = [step.name for step in steps]\n",
    "    if len(steps) == 1:\n",
    "        steps.append(FuncDetails(\"end\", None, None, False, \"\", \"pass\"))\n",
    "    params = params_as_dict(nb_path)\n",
    "    if len(params) == 0:\n",
    "        print(f\"No params cell found for: {os.path.basename(nb_path)}\")\n",
    "    flow_class_name = f\"{titleize(extract_module_only(module_name))}Flow\"\n",
    "    rename_steps_for_metaflow(steps)\n",
    "    write_module_to_file(\n",
    "        flow_path,\n",
    "        flow_class_name,\n",
    "        lib_name,\n",
    "        module_name,\n",
    "        orig_step_names,\n",
    "        steps,\n",
    "        params,\n",
    "        track_experiment,\n",
    "    )\n",
    "    if not silent:\n",
    "        print(\n",
    "            f\"Converted {nb_name} to {flow_class_name} in: {os.path.basename(flow_path)}\"\n",
    "        )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 382,
   "metadata": {},
   "outputs": [],
   "source": [
    "pkg_module_name = \"test.module\"\n",
    "module_name = \"module\"\n",
    "path_sep_module_name = module_name.replace(\".\", \"/\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 383,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def extract_module_only(package_module_name):\n",
    "    module_name = package_module_name\n",
    "    if \".\" in module_name:\n",
    "        package_name, module_name = module_name.split(\".\")\n",
    "    return module_name"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 384,
   "metadata": {},
   "outputs": [],
   "source": [
    "assert \"module\" == extract_module_only(module_name)\n",
    "assert \"module\" == extract_module_only(pkg_module_name)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 385,
   "metadata": {},
   "outputs": [],
   "source": [
    "#  export\n",
    "\n",
    "\n",
    "def write_module_to_file(\n",
    "    flow_path: Path,\n",
    "    flow_class_name: str,\n",
    "    lib_name: str,\n",
    "    module_name: str,\n",
    "    orig_step_names: Iterable[str],\n",
    "    steps: Iterable[FuncDetails],\n",
    "    params: dict,\n",
    "    track_experiment: bool,\n",
    "):\n",
    "    if not os.path.exists(flow_path.parent):\n",
    "        os.mkdir(flow_path.parent)\n",
    "    fq_module_name = f\"{lib_name}.{module_name}\"\n",
    "    param_meta = extract_param_meta(fq_module_name, params)\n",
    "    with open(flow_path, \"w\") as flow_file:\n",
    "        flow_file.write(\"#!/usr/bin/env python\\n\")\n",
    "        flow_file.write(\"# coding=utf-8\\n\")\n",
    "        flow_file.write(\"# SCIFLOW GENERATED FILE - EDIT COMPANION NOTEBOOK\\n\")\n",
    "        has_mf_param = any((p.has_metaflow_param for p in param_meta.values()))\n",
    "        has_json_param = any((p.is_json_type for p in param_meta.values()))\n",
    "        mf_params_import = \"from metaflow import FlowSpec, step, current\"\n",
    "        if has_mf_param:\n",
    "            mf_params_import += \", Parameter\"\n",
    "        if has_json_param:\n",
    "            mf_params_import += \", JSONType\"\n",
    "            flow_file.write(\"import json\\n\")\n",
    "        flow_file.write(mf_params_import + \"\\n\")\n",
    "        flow_file.write(f\"from {fq_module_name} import {', '.join(orig_step_names)}\\n\")\n",
    "        if len(params) > 0:\n",
    "            flow_file.write(\n",
    "                f\"from {fq_module_name} import {', '.join(params.keys())}\\n\"\n",
    "            )\n",
    "\n",
    "        if track_experiment:\n",
    "            flow_file.write(\"from sacred import Experiment\\n\")\n",
    "            flow_file.write(\"from sciflow.lake_observer import AWSLakeObserver\\n\")\n",
    "            flow_file.write(\"import time\")\n",
    "            write_observers(flow_file, module_name, Config().bucket, Config().lib_name)\n",
    "\n",
    "        flow_file.write(f\"\\n\\nclass {flow_class_name}(FlowSpec):\\n\")\n",
    "        single_indent = \"    \"\n",
    "        write_params(flow_file, param_meta, single_indent)\n",
    "        flow_file.write(f\"{single_indent}artifacts = []\\n\")\n",
    "        flow_file.write(f\"{single_indent}metrics = []\\n\")\n",
    "        flow_file.write(\"\\n\")\n",
    "        write_steps(flow_file, steps, orig_step_names, param_meta, single_indent)\n",
    "        write_track_flow(flow_file, track_experiment)\n",
    "        flow_file.write(\"\\n\")\n",
    "\n",
    "        flow_file.write('if __name__ == \"__main__\":\\n')\n",
    "        flow_file.write(f\"{single_indent}{flow_class_name}()\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 386,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def write_observers(flow_file, module_name, bucket_name, project):\n",
    "    experiment_name = extract_module_only(module_name)\n",
    "    sacred_setup = f\"\"\"\n",
    "\n",
    "ex = Experiment(\"{experiment_name}\")\n",
    "# TODO inject observers\n",
    "obs = AWSLakeObserver(experiment_name=\"{experiment_name}\")\n",
    "ex.observers.append(obs)\n",
    "\n",
    "@ex.config\n",
    "def config():\n",
    "    flow_run_id = None\n",
    "    artifacts = []\n",
    "    metrics = []\n",
    "    \"\"\"\n",
    "    flow_file.write(sacred_setup)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 387,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def write_track_flow(flow_file, track_experiment):\n",
    "    track_flow = \"\"\"\n",
    "    @step\n",
    "    def end(self):\n",
    "        flow_info = {\n",
    "            \"flow_name\": current.flow_name,\n",
    "            \"run id\": current.run_id,\n",
    "            \"origin run id\": current.origin_run_id,\n",
    "            \"pathspec\": current.pathspec,\n",
    "            \"namespace\": current.namespace,\n",
    "            \"username\": current.username,\n",
    "            \"flow parameters\": str(current.parameter_names),\n",
    "            \"run_time_mins\": round((time.time() - self.__getattr__('start_time')) / 60.0, 1)\n",
    "        }\n",
    "    \n",
    "        run = ex.run(config_updates={'artifacts': self.__getattr__('artifacts'),\n",
    "                                    'metrics': self.__getattr__('metrics')},\n",
    "                     meta_info = flow_info)\n",
    "        \n",
    "    @ex.main\n",
    "    def track_flow(artifacts, metrics, _run):\n",
    "        for artifact in artifacts:\n",
    "            _run.add_artifact(artifact)\n",
    "        for metric_name, metric_value, step in metrics:\n",
    "            _run.log_scalar(metric_name, metric_value, step)\n",
    "    \"\"\"\n",
    "    if not track_experiment:\n",
    "        track_flow = \"\"\"\n",
    "    @step\n",
    "    def end(self):\n",
    "        pass\n",
    "    \"\"\"\n",
    "    flow_file.write(track_flow)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 388,
   "metadata": {},
   "outputs": [],
   "source": [
    "#  export\n",
    "\n",
    "\n",
    "def write_params(flow_file, param_meta, single_indent):\n",
    "    for param in param_meta.keys():\n",
    "        if param_meta[param].is_scalar:\n",
    "            flow_file.write(\n",
    "                f\"{single_indent}{param} = Parameter('{param}', default={param})\\n\"\n",
    "            )\n",
    "        elif param_meta[param].is_json_type:\n",
    "            flow_file.write(\n",
    "                f\"{single_indent}{param} = Parameter('{param}', default=json.dumps({param}), type=JSONType)\\n\"\n",
    "            )\n",
    "        elif param_meta[param].instance_type == PosixPath:\n",
    "            flow_file.write(\n",
    "                f\"{single_indent}{param} = Parameter('{param}', default=str({param}))\\n\"\n",
    "            )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 389,
   "metadata": {},
   "outputs": [],
   "source": [
    "nb_path = os.path.join(Path(\".\").resolve(), \"test\", \"test_data_handling.ipynb\")\n",
    "params = params_as_dict(nb_path)\n",
    "param_meta = extract_param_meta(\"sciflow.test.test_data_handling\", params)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 390,
   "metadata": {},
   "outputs": [],
   "source": [
    "assert any((p.has_metaflow_param for p in param_meta.values()))\n",
    "assert any((p.is_json_type for p in param_meta.values()))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 391,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def format_arg(arg, param_meta):\n",
    "    if arg in param_meta and not param_meta[arg].has_metaflow_param:\n",
    "        result = arg\n",
    "    else:\n",
    "        result = \"self.\" + arg\n",
    "    return result\n",
    "\n",
    "\n",
    "def write_steps(flow_file, steps, orig_step_names, param_meta, single_indent):\n",
    "    for i, step in enumerate(steps):\n",
    "        flow_file.write(f\"{single_indent}@step\\n\")\n",
    "        flow_file.write(f\"{single_indent}def {step.name}(self):\\n\")\n",
    "        if step.docstring:\n",
    "            flow_file.write(f\"{indent_multiline(step.docstring, 2)}\\n\")\n",
    "        # Check for padded step\n",
    "        if i < len(orig_step_names):\n",
    "            flow_step_args = \"\"\n",
    "            if len(step.args) > 0:\n",
    "                flow_step_args = \", \".join(\n",
    "                    [format_arg(a, param_meta) for a in step.args.split(\",\")]\n",
    "                )\n",
    "            if not step.has_return:\n",
    "                flow_file.write(\n",
    "                    f\"{single_indent}{single_indent}{orig_step_names[i]}({flow_step_args})\\n\"\n",
    "                )\n",
    "            else:\n",
    "                if step.return_stmt in param_meta:\n",
    "                    raise ValueError(\n",
    "                        f\"[{os.path.basename(flow_file.name)}] step return variable {step.return_stmt} shadows a parameter name - parameters must be unique\"\n",
    "                    )\n",
    "                flow_file.write(\n",
    "                    f\"{single_indent}{single_indent}results = {orig_step_names[i]}({flow_step_args})\\n\"\n",
    "                )\n",
    "                write_track_capture(flow_file)\n",
    "        if i == 0:\n",
    "            flow_file.write(\n",
    "                f\"{single_indent}{single_indent}self.start_time = time.time()\\n\"\n",
    "            )\n",
    "        if i < len(steps):\n",
    "            next_step = \"end\" if i == len(steps) - 1 else steps[i + 1].name\n",
    "            flow_file.write(\n",
    "                f\"{single_indent}{single_indent}self.next(self.{next_step})\\n\"\n",
    "            )\n",
    "        flow_file.write(\"\\n\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 392,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def write_track_capture(flow_file):\n",
    "    flow_file.write(\n",
    "        f\"\"\"\n",
    "        for key in results.keys():\n",
    "            if key in self.__dict__:\n",
    "                self.__dict__[key] = self.__dict__[key] + results[key]\n",
    "            else:\n",
    "                self.__dict__[key] = results[key]\n",
    "\n",
    "\"\"\"\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 393,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def get_module_name(nb_path):\n",
    "    nb = read_nb(nb_path)\n",
    "    module_name = find_default_export(nb[\"cells\"])\n",
    "    return module_name"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Test Flow Generation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 394,
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_flow_path(nb_path):\n",
    "    return Path(\n",
    "        os.path.join(\n",
    "            Config().path(\"flows_path\"),\n",
    "            f\"{get_module_name(nb_path).split('.')[-1]}.py\",\n",
    "        )\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 395,
   "metadata": {},
   "outputs": [],
   "source": [
    "assert Path(\n",
    "    \"/home/jovyan/git/sciflow/nbs/test/flows/test_data_handling.py\"\n",
    ") == get_flow_path(nb_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 396,
   "metadata": {},
   "outputs": [],
   "source": [
    "flow_path = Path(\n",
    "    os.path.join(\n",
    "        Path(\".\").resolve(),\n",
    "        \"test\",\n",
    "        \"flows\",\n",
    "        f\"{get_module_name(nb_path).split('.')[-1]}.py\",\n",
    "    )\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 397,
   "metadata": {},
   "outputs": [],
   "source": [
    "assert (\n",
    "    Path(os.path.join(Path(\".\").resolve(), \"test\", \"flows\", \"test_data_handling.py\",))\n",
    "    == flow_path\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 398,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Converted test_data_handling.ipynb to TestDataHandlingFlow in: test_data_handling.py\n"
     ]
    }
   ],
   "source": [
    "nb_to_metaflow(nb_path, flow_path, silent=False, track_experiment=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 399,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Converted test_clustering.ipynb to TestClusteringFlow in: test_clustering.py\n"
     ]
    }
   ],
   "source": [
    "nb_to_metaflow(\n",
    "    Path(\"/home/jovyan/git/sciflow/nbs/test/test_clustering.ipynb\"),\n",
    "    Path(\"/home/jovyan/git/sciflow/nbs/test/flows/test_clustering.py\"),\n",
    "    silent=False,\n",
    "    track_experiment=True,\n",
    ")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Ignore notebooks without Sciflow steps"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 400,
   "metadata": {},
   "outputs": [],
   "source": [
    "nb_to_metaflow(\"packaging.ipynb\", flow_path, silent=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 401,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def generate_flows(config: Config):\n",
    "    flows_dir = config.path(\"flows_path\")\n",
    "    nb_paths = nbglob(recursive=True)\n",
    "    for nb_path in nb_paths:\n",
    "        flow_module_name = os.path.basename(nb_path).replace(\"ipynb\", \"py\")\n",
    "        nb_to_metaflow(\n",
    "            nb_path, Path(os.path.join(flows_dir, flow_module_name)), silent=False\n",
    "        )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 402,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No params cell found for: test_clustering_no_params.ipynb\n",
      "Converted test_clustering_no_params.ipynb to TestClusteringNoParamsFlow in: test_clustering_no_params.py\n",
      "Converted test_clustering.ipynb to TestClusteringFlow in: test_clustering.py\n",
      "Converted test_export.ipynb to TestExportFlow in: test_export.py\n",
      "Converted test_module.ipynb to TestModuleFlow in: test_module.py\n",
      "Converted test_data_handling.ipynb to TestDataHandlingFlow in: test_data_handling.py\n"
     ]
    }
   ],
   "source": [
    "generate_flows(Config(cfg_name=\"test/settings.ini\"))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 403,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "@call_parse\n",
    "def sciflow_generate():\n",
    "    generate_flows(Config())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Verify Flow Generation\n",
    "\n",
    "> Check that flows are valid and that they run. Running is a longer operation so be careful not to overload your build with slow cycles."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 404,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def check_flows(config, flow_command=\"show\", ignore_suffix=\"_no_params.py\"):\n",
    "    flow_results = {}\n",
    "    flows_dir = config.path(\"flows_path\")\n",
    "    if ignore_suffix:\n",
    "        flow_paths = [p for p in os.listdir(flows_dir) if not p.endswith(ignore_suffix)]\n",
    "    else:\n",
    "        flow_paths = os.listdir(flows_dir)\n",
    "    for flow_path in flow_paths:\n",
    "        flow_name = os.path.basename(flow_path)\n",
    "        if flow_path.endswith(\".py\"):\n",
    "            ret_code, output = check_flow(\n",
    "                flows_dir, flow_path, flow_command=flow_command\n",
    "            )\n",
    "            flow_results[flow_name] = ret_code, output\n",
    "            if ret_code == 0:\n",
    "                print(f\"Flow: {flow_name} {flow_command} verified\")\n",
    "            else:\n",
    "                print(\n",
    "                    f\"Flow: {flow_name} {flow_command} verification failed\\nDetails:\\n{output}\"\n",
    "                )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 405,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def prep_mf_env():\n",
    "    if \"USER\" not in os.environ:\n",
    "        try:\n",
    "            os.environ[\"USER\"] = os.environ[\"GIT_COMMITTER_NAME\"]\n",
    "        except KeyError:\n",
    "            raise EnvironmentError(\n",
    "                \"Metaflow requires a known user for tracked execution. Add USER or GIT_COMMITTER_NAME to Jupyter environment variables\"\n",
    "            )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 406,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def run_shell_cmd(script):\n",
    "    pipe = subprocess.Popen(\n",
    "        \"%s\" % script, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=True\n",
    "    )\n",
    "    output = pipe.communicate()[0]\n",
    "    return pipe, output.decode(\"utf-8\").strip()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 407,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def check_flow(flows_dir, flow_module, flow_command=\"show\", params=None):\n",
    "    prep_mf_env()\n",
    "    if params:\n",
    "        args = \" \".join([f\"--{p[0]} {p[1]}\" for p in params])\n",
    "        script = (\n",
    "            f\"python '{os.path.join(flows_dir, flow_module)}' {flow_command} {args}\"\n",
    "        )\n",
    "    else:\n",
    "        script = f\"python '{os.path.join(flows_dir, flow_module)}' {flow_command}\"\n",
    "    pipe, output = run_shell_cmd(script)\n",
    "    return pipe.returncode, output"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 408,
   "metadata": {},
   "outputs": [],
   "source": [
    "params = [(\"speed\", \"fast\"), (\"traffic_percent\", 10)]\n",
    "assert \"--speed fast --traffic_percent 10\" == \" \".join(\n",
    "    [f\"--{p[0]} {p[1]}\" for p in params]\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 409,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Flow: test_module.py show verified\n",
      "Flow: test_clustering_no_params.py show verified\n",
      "Flow: test_clustering.py show verified\n",
      "Flow: test_data_handling.py show verified\n",
      "Flow: test_export.py show verified\n"
     ]
    }
   ],
   "source": [
    "check_flows(Config(cfg_name=\"test/settings.ini\"), ignore_suffix=None)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 410,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Flow: test_module.py --no-pylint run verification failed\n",
      "Details:\n",
      "Metaflow 2.2.7 executing TestModuleFlow for user:e02079\n",
      "Validating your flow...\n",
      "    The graph looks good!\n",
      "2021-04-22 13:54:47.250 Workflow starting (run-id 1619099687246855):\n",
      "2021-04-22 13:54:47.255 [1619099687246855/start/1 (pid 6974)] Task is starting.\n",
      "2021-04-22 13:54:48.245 [1619099687246855/start/1 (pid 6974)] 2\n",
      "2021-04-22 13:54:48.402 [1619099687246855/start/1 (pid 6974)] Task finished successfully.\n",
      "2021-04-22 13:54:48.408 [1619099687246855/end/2 (pid 6986)] Task is starting.\n",
      "2021-04-22 13:54:49.409 [1619099687246855/end/2 (pid 6986)] INFO - test_module - Running command 'track_flow'\n",
      "2021-04-22 13:54:49.412 [1619099687246855/end/2 (pid 6986)] ERROR - test_module - Failed after 0:00:00!\n",
      "2021-04-22 13:54:49.413 [1619099687246855/end/2 (pid 6986)] ERROR - test_module - Traceback (most recent call last):\n",
      "2021-04-22 13:54:49.416 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 235, in __call__\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)]     self._emit_started()\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 333, in _emit_started\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)]     _id=self._id,\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 194, in started_event\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)]     _id = self._determine_run_dir(_id)\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 135, in _determine_run_dir\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)]     self.s3, self.bucket_name, s3_join(self.experiments_key_prefix, \"runs\")\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/git/text_discovery/steps/text_discovery/s3_utils.py\", line 69, in list_s3_subdirs\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)]     bucket = s3_res.Bucket(bucket_name)\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/factory.py\", line 474, in create_resource\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)]     client=self.meta.client)(*args, **kwargs)\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/base.py\", line 119, in __init__\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)]     'Required parameter {0} not set'.format(identifier))\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)] ValueError: Required parameter name not set\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)] \n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)] During handling of the above exception, another exception occurred:\n",
      "2021-04-22 13:54:49.417 [1619099687246855/end/2 (pid 6986)] \n",
      "2021-04-22 13:54:49.418 [1619099687246855/end/2 (pid 6986)] Traceback (most recent call last):\n",
      "2021-04-22 13:54:49.418 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 429, in _final_call\n",
      "2021-04-22 13:54:49.418 [1619099687246855/end/2 (pid 6986)]     getattr(observer, method)(**kwargs)\n",
      "2021-04-22 13:54:49.418 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 244, in failed_event\n",
      "2021-04-22 13:54:49.418 [1619099687246855/end/2 (pid 6986)]     self.run_entry[\"stop_time\"] = fail_time.isoformat()\n",
      "2021-04-22 13:54:49.418 [1619099687246855/end/2 (pid 6986)] TypeError: 'NoneType' object does not support item assignment\n",
      "2021-04-22 13:54:49.418 [1619099687246855/end/2 (pid 6986)] \n",
      "2021-04-22 13:54:49.418 [1619099687246855/end/2 (pid 6986)] <flow TestModuleFlow step end> failed:\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)]     Internal error\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)] Traceback (most recent call last):\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/cli.py\", line 930, in main\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)]     start(auto_envvar_prefix='METAFLOW', obj=state)\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 829, in __call__\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)]     return self.main(args, kwargs)\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 782, in main\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)]     rv = self.invoke(ctx)\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 1259, in invoke\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)]     return _process_result(sub_ctx.command.invoke(sub_ctx))\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 1066, in invoke\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)]     return ctx.invoke(self.callback, ctx.params)\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 610, in invoke\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)]     return callback(args, kwargs)\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/decorators.py\", line 33, in new_func\n",
      "2021-04-22 13:54:49.574 [1619099687246855/end/2 (pid 6986)]     return f(get_current_context().obj, args, kwargs)\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/cli.py\", line 447, in step\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]     max_user_code_retries)\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/task.py\", line 396, in run_step\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]     self._exec_step_function(step_func)\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/task.py\", line 47, in _exec_step_function\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]     step_function()\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/git/sciflow/nbs/test/flows/test_module.py\", line 61, in end\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]     meta_info = flow_info)\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/experiment.py\", line 276, in run\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]     run()\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 235, in __call__\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]     self._emit_started()\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 333, in _emit_started\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]     _id=self._id,\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 194, in started_event\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]     _id = self._determine_run_dir(_id)\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 135, in _determine_run_dir\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]     self.s3, self.bucket_name, s3_join(self.experiments_key_prefix, \"runs\")\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/git/text_discovery/steps/text_discovery/s3_utils.py\", line 69, in list_s3_subdirs\n",
      "2021-04-22 13:54:49.575 [1619099687246855/end/2 (pid 6986)]     bucket = s3_res.Bucket(bucket_name)\n",
      "2021-04-22 13:54:49.576 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/factory.py\", line 474, in create_resource\n",
      "2021-04-22 13:54:49.576 [1619099687246855/end/2 (pid 6986)]     client=self.meta.client)(args, kwargs)\n",
      "2021-04-22 13:54:49.576 [1619099687246855/end/2 (pid 6986)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/base.py\", line 119, in __init__\n",
      "2021-04-22 13:54:49.576 [1619099687246855/end/2 (pid 6986)]     'Required parameter {0} not set'.format(identifier))\n",
      "2021-04-22 13:54:49.576 [1619099687246855/end/2 (pid 6986)] ValueError: Required parameter name not set\n",
      "2021-04-22 13:54:49.576 [1619099687246855/end/2 (pid 6986)] \n",
      "2021-04-22 13:54:49.578 [1619099687246855/end/2 (pid 6986)] Task failed.\n",
      "2021-04-22 13:54:49.578 Workflow failed.\n",
      "2021-04-22 13:54:49.578 Terminating 0 active tasks...\n",
      "2021-04-22 13:54:49.578 Flushing logs...\n",
      "    Step failure:\n",
      "    Step end (task-id 2) failed.\n",
      "Flow: test_clustering.py --no-pylint run verification failed\n",
      "Details:\n",
      "Metaflow 2.2.7 executing TestClusteringFlow for user:e02079\n",
      "Validating your flow...\n",
      "    The graph looks good!\n",
      "2021-04-22 13:54:51.787 Workflow starting (run-id 1619099691784371):\n",
      "2021-04-22 13:54:51.793 [1619099691784371/start/1 (pid 7018)] Task is starting.\n",
      "2021-04-22 13:54:54.029 [1619099691784371/start/1 (pid 7018)] Task finished successfully.\n",
      "2021-04-22 13:54:54.035 [1619099691784371/preprocess/2 (pid 7033)] Task is starting.\n",
      "2021-04-22 13:55:21.274 [1619099691784371/preprocess/2 (pid 7033)] Task finished successfully.\n",
      "2021-04-22 13:55:21.282 [1619099691784371/fit/3 (pid 7066)] Task is starting.\n",
      "2021-04-22 13:55:23.669 [1619099691784371/fit/3 (pid 7066)] Task finished successfully.\n",
      "2021-04-22 13:55:23.676 [1619099691784371/evaluate/4 (pid 7081)] Task is starting.\n",
      "2021-04-22 13:55:26.062 [1619099691784371/evaluate/4 (pid 7081)] Task finished successfully.\n",
      "2021-04-22 13:55:26.069 [1619099691784371/end/5 (pid 7096)] Task is starting.\n",
      "2021-04-22 13:55:28.105 [1619099691784371/end/5 (pid 7096)] INFO:test_clustering:Running command 'track_flow'\n",
      "2021-04-22 13:55:28.109 [1619099691784371/end/5 (pid 7096)] ERROR:test_clustering:Failed after 0:00:00!\n",
      "2021-04-22 13:55:28.109 [1619099691784371/end/5 (pid 7096)] ERROR:test_clustering:Traceback (most recent call last):\n",
      "2021-04-22 13:55:28.114 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 235, in __call__\n",
      "2021-04-22 13:55:28.114 [1619099691784371/end/5 (pid 7096)]     self._emit_started()\n",
      "2021-04-22 13:55:28.114 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 333, in _emit_started\n",
      "2021-04-22 13:55:28.114 [1619099691784371/end/5 (pid 7096)]     _id=self._id,\n",
      "2021-04-22 13:55:28.114 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 194, in started_event\n",
      "2021-04-22 13:55:28.114 [1619099691784371/end/5 (pid 7096)]     _id = self._determine_run_dir(_id)\n",
      "2021-04-22 13:55:28.114 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 135, in _determine_run_dir\n",
      "2021-04-22 13:55:28.114 [1619099691784371/end/5 (pid 7096)]     self.s3, self.bucket_name, s3_join(self.experiments_key_prefix, \"runs\")\n",
      "2021-04-22 13:55:28.114 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/git/text_discovery/steps/text_discovery/s3_utils.py\", line 69, in list_s3_subdirs\n",
      "2021-04-22 13:55:28.114 [1619099691784371/end/5 (pid 7096)]     bucket = s3_res.Bucket(bucket_name)\n",
      "2021-04-22 13:55:28.114 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/factory.py\", line 474, in create_resource\n",
      "2021-04-22 13:55:28.114 [1619099691784371/end/5 (pid 7096)]     client=self.meta.client)(*args, **kwargs)\n",
      "2021-04-22 13:55:28.114 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/base.py\", line 119, in __init__\n",
      "2021-04-22 13:55:28.115 [1619099691784371/end/5 (pid 7096)]     'Required parameter {0} not set'.format(identifier))\n",
      "2021-04-22 13:55:28.115 [1619099691784371/end/5 (pid 7096)] ValueError: Required parameter name not set\n",
      "2021-04-22 13:55:28.115 [1619099691784371/end/5 (pid 7096)] \n",
      "2021-04-22 13:55:28.115 [1619099691784371/end/5 (pid 7096)] During handling of the above exception, another exception occurred:\n",
      "2021-04-22 13:55:28.115 [1619099691784371/end/5 (pid 7096)] \n",
      "2021-04-22 13:55:28.115 [1619099691784371/end/5 (pid 7096)] Traceback (most recent call last):\n",
      "2021-04-22 13:55:28.115 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 429, in _final_call\n",
      "2021-04-22 13:55:28.115 [1619099691784371/end/5 (pid 7096)]     getattr(observer, method)(**kwargs)\n",
      "2021-04-22 13:55:28.115 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 244, in failed_event\n",
      "2021-04-22 13:55:28.115 [1619099691784371/end/5 (pid 7096)]     self.run_entry[\"stop_time\"] = fail_time.isoformat()\n",
      "2021-04-22 13:55:28.115 [1619099691784371/end/5 (pid 7096)] TypeError: 'NoneType' object does not support item assignment\n",
      "2021-04-22 13:55:28.115 [1619099691784371/end/5 (pid 7096)] \n",
      "2021-04-22 13:55:28.115 [1619099691784371/end/5 (pid 7096)] <flow TestClusteringFlow step end> failed:\n",
      "2021-04-22 13:55:28.390 [1619099691784371/end/5 (pid 7096)]     Internal error\n",
      "2021-04-22 13:55:28.390 [1619099691784371/end/5 (pid 7096)] Traceback (most recent call last):\n",
      "2021-04-22 13:55:28.390 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/cli.py\", line 930, in main\n",
      "2021-04-22 13:55:28.390 [1619099691784371/end/5 (pid 7096)]     start(auto_envvar_prefix='METAFLOW', obj=state)\n",
      "2021-04-22 13:55:28.390 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 829, in __call__\n",
      "2021-04-22 13:55:28.390 [1619099691784371/end/5 (pid 7096)]     return self.main(args, kwargs)\n",
      "2021-04-22 13:55:28.390 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 782, in main\n",
      "2021-04-22 13:55:28.390 [1619099691784371/end/5 (pid 7096)]     rv = self.invoke(ctx)\n",
      "2021-04-22 13:55:28.390 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 1259, in invoke\n",
      "2021-04-22 13:55:28.390 [1619099691784371/end/5 (pid 7096)]     return _process_result(sub_ctx.command.invoke(sub_ctx))\n",
      "2021-04-22 13:55:28.390 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 1066, in invoke\n",
      "2021-04-22 13:55:28.390 [1619099691784371/end/5 (pid 7096)]     return ctx.invoke(self.callback, ctx.params)\n",
      "2021-04-22 13:55:28.390 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 610, in invoke\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]     return callback(args, kwargs)\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/decorators.py\", line 33, in new_func\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]     return f(get_current_context().obj, args, kwargs)\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/cli.py\", line 447, in step\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]     max_user_code_retries)\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/task.py\", line 396, in run_step\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]     self._exec_step_function(step_func)\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/task.py\", line 47, in _exec_step_function\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]     step_function()\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/git/sciflow/nbs/test/flows/test_clustering.py\", line 90, in end\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]     meta_info = flow_info)\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/experiment.py\", line 276, in run\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]     run()\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 235, in __call__\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]     self._emit_started()\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 333, in _emit_started\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]     _id=self._id,\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 194, in started_event\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]     _id = self._determine_run_dir(_id)\n",
      "2021-04-22 13:55:28.391 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 135, in _determine_run_dir\n",
      "2021-04-22 13:55:28.392 [1619099691784371/end/5 (pid 7096)]     self.s3, self.bucket_name, s3_join(self.experiments_key_prefix, \"runs\")\n",
      "2021-04-22 13:55:28.392 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/git/text_discovery/steps/text_discovery/s3_utils.py\", line 69, in list_s3_subdirs\n",
      "2021-04-22 13:55:28.392 [1619099691784371/end/5 (pid 7096)]     bucket = s3_res.Bucket(bucket_name)\n",
      "2021-04-22 13:55:28.392 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/factory.py\", line 474, in create_resource\n",
      "2021-04-22 13:55:28.392 [1619099691784371/end/5 (pid 7096)]     client=self.meta.client)(args, kwargs)\n",
      "2021-04-22 13:55:28.392 [1619099691784371/end/5 (pid 7096)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/base.py\", line 119, in __init__\n",
      "2021-04-22 13:55:28.392 [1619099691784371/end/5 (pid 7096)]     'Required parameter {0} not set'.format(identifier))\n",
      "2021-04-22 13:55:28.392 [1619099691784371/end/5 (pid 7096)] ValueError: Required parameter name not set\n",
      "2021-04-22 13:55:28.392 [1619099691784371/end/5 (pid 7096)] \n",
      "2021-04-22 13:55:28.393 [1619099691784371/end/5 (pid 7096)] Task failed.\n",
      "2021-04-22 13:55:28.393 Workflow failed.\n",
      "2021-04-22 13:55:28.393 Terminating 0 active tasks...\n",
      "2021-04-22 13:55:28.393 Flushing logs...\n",
      "    Step failure:\n",
      "    Step end (task-id 5) failed.\n",
      "Flow: test_data_handling.py --no-pylint run verification failed\n",
      "Details:\n",
      "Metaflow 2.2.7 executing TestDataHandlingFlow for user:e02079\n",
      "Validating your flow...\n",
      "    The graph looks good!\n",
      "2021-04-22 13:55:34.556 Workflow starting (run-id 1619099734552001):\n",
      "2021-04-22 13:55:34.647 [1619099734552001/start/1 (pid 7132)] Task is starting.\n",
      "2021-04-22 13:55:40.147 [1619099734552001/start/1 (pid 7132)] int_param: 3\n",
      "2021-04-22 13:55:41.113 [1619099734552001/start/1 (pid 7132)] float_param: 1.1\n",
      "2021-04-22 13:55:41.113 [1619099734552001/start/1 (pid 7132)] str_param: Sciflow 🔬\n",
      "2021-04-22 13:55:41.114 [1619099734552001/start/1 (pid 7132)] Task finished successfully.\n",
      "2021-04-22 13:55:41.205 [1619099734552001/py_advanced/2 (pid 7144)] Task is starting.\n",
      "2021-04-22 13:55:46.698 [1619099734552001/py_advanced/2 (pid 7144)] input_path: /home/jovyan/git/sciflow/nbs\n",
      "2021-04-22 13:55:47.680 [1619099734552001/py_advanced/2 (pid 7144)] input_path: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]\n",
      "2021-04-22 13:55:47.680 [1619099734552001/py_advanced/2 (pid 7144)] input_path: {'a': {'b': {'c': 'abc'}}, 'another_key': [1, 2, 3]}\n",
      "2021-04-22 13:55:47.682 [1619099734552001/py_advanced/2 (pid 7144)] Task finished successfully.\n",
      "2021-04-22 13:55:47.775 [1619099734552001/pandas/3 (pid 7156)] Task is starting.\n",
      "2021-04-22 13:55:53.279 [1619099734552001/pandas/3 (pid 7156)] series: (10000000,)\n",
      "2021-04-22 13:55:54.255 [1619099734552001/pandas/3 (pid 7156)] df: (10000000, 4)\n",
      "2021-04-22 13:55:54.256 [1619099734552001/pandas/3 (pid 7156)] Task finished successfully.\n",
      "2021-04-22 13:55:54.347 [1619099734552001/end/4 (pid 7168)] Task is starting.\n",
      "2021-04-22 13:56:00.093 [1619099734552001/end/4 (pid 7168)] INFO - test_data_handling - Running command 'track_flow'\n",
      "2021-04-22 13:56:00.096 [1619099734552001/end/4 (pid 7168)] ERROR - test_data_handling - Failed after 0:00:00!\n",
      "2021-04-22 13:56:00.097 [1619099734552001/end/4 (pid 7168)] ERROR - test_data_handling - Traceback (most recent call last):\n",
      "2021-04-22 13:56:00.101 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 235, in __call__\n",
      "2021-04-22 13:56:00.101 [1619099734552001/end/4 (pid 7168)]     self._emit_started()\n",
      "2021-04-22 13:56:00.101 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 333, in _emit_started\n",
      "2021-04-22 13:56:00.101 [1619099734552001/end/4 (pid 7168)]     _id=self._id,\n",
      "2021-04-22 13:56:00.101 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 194, in started_event\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)]     _id = self._determine_run_dir(_id)\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 135, in _determine_run_dir\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)]     self.s3, self.bucket_name, s3_join(self.experiments_key_prefix, \"runs\")\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/git/text_discovery/steps/text_discovery/s3_utils.py\", line 69, in list_s3_subdirs\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)]     bucket = s3_res.Bucket(bucket_name)\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/factory.py\", line 474, in create_resource\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)]     client=self.meta.client)(*args, **kwargs)\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/base.py\", line 119, in __init__\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)]     'Required parameter {0} not set'.format(identifier))\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)] ValueError: Required parameter name not set\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)] \n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)] During handling of the above exception, another exception occurred:\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)] \n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)] Traceback (most recent call last):\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 429, in _final_call\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)]     getattr(observer, method)(**kwargs)\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 244, in failed_event\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)]     self.run_entry[\"stop_time\"] = fail_time.isoformat()\n",
      "2021-04-22 13:56:00.102 [1619099734552001/end/4 (pid 7168)] TypeError: 'NoneType' object does not support item assignment\n",
      "2021-04-22 13:56:00.103 [1619099734552001/end/4 (pid 7168)] \n",
      "2021-04-22 13:56:00.103 [1619099734552001/end/4 (pid 7168)] <flow TestDataHandlingFlow step end> failed:\n",
      "2021-04-22 13:56:01.083 [1619099734552001/end/4 (pid 7168)]     Internal error\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)] Traceback (most recent call last):\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/cli.py\", line 930, in main\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]     start(auto_envvar_prefix='METAFLOW', obj=state)\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 829, in __call__\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]     return self.main(args, kwargs)\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 782, in main\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]     rv = self.invoke(ctx)\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 1259, in invoke\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]     return _process_result(sub_ctx.command.invoke(sub_ctx))\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 1066, in invoke\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]     return ctx.invoke(self.callback, ctx.params)\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 610, in invoke\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]     return callback(args, kwargs)\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/decorators.py\", line 33, in new_func\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]     return f(get_current_context().obj, args, kwargs)\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/cli.py\", line 447, in step\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]     max_user_code_retries)\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/task.py\", line 396, in run_step\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]     self._exec_step_function(step_func)\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/task.py\", line 47, in _exec_step_function\n",
      "2021-04-22 13:56:01.084 [1619099734552001/end/4 (pid 7168)]     step_function()\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/git/sciflow/nbs/test/flows/test_data_handling.py\", line 74, in end\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]     meta_info = flow_info)\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/experiment.py\", line 276, in run\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]     run()\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 235, in __call__\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]     self._emit_started()\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 333, in _emit_started\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]     _id=self._id,\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 194, in started_event\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]     _id = self._determine_run_dir(_id)\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 135, in _determine_run_dir\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]     self.s3, self.bucket_name, s3_join(self.experiments_key_prefix, \"runs\")\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/git/text_discovery/steps/text_discovery/s3_utils.py\", line 69, in list_s3_subdirs\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]     bucket = s3_res.Bucket(bucket_name)\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/factory.py\", line 474, in create_resource\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]     client=self.meta.client)(args, kwargs)\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/base.py\", line 119, in __init__\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)]     'Required parameter {0} not set'.format(identifier))\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)] ValueError: Required parameter name not set\n",
      "2021-04-22 13:56:01.085 [1619099734552001/end/4 (pid 7168)] \n",
      "2021-04-22 13:56:01.086 [1619099734552001/end/4 (pid 7168)] Task failed.\n",
      "2021-04-22 13:56:01.086 Workflow failed.\n",
      "2021-04-22 13:56:01.087 Terminating 0 active tasks...\n",
      "2021-04-22 13:56:01.087 Flushing logs...\n",
      "    Step failure:\n",
      "    Step end (task-id 4) failed.\n",
      "Flow: test_export.py --no-pylint run verification failed\n",
      "Details:\n",
      "Metaflow 2.2.7 executing TestExportFlow for user:e02079\n",
      "Validating your flow...\n",
      "    The graph looks good!\n",
      "2021-04-22 13:56:07.346 Workflow starting (run-id 1619099767342119):\n",
      "2021-04-22 13:56:07.351 [1619099767342119/start/1 (pid 7197)] Task is starting.\n",
      "2021-04-22 13:56:12.378 [1619099767342119/start/1 (pid 7197)] 3\n",
      "2021-04-22 13:56:12.563 [1619099767342119/start/1 (pid 7197)] Task finished successfully.\n",
      "2021-04-22 13:56:12.568 [1619099767342119/preprocess/2 (pid 7209)] Task is starting.\n",
      "2021-04-22 13:56:18.593 [1619099767342119/preprocess/2 (pid 7209)] Preprocessing input data from /home/jovyan/git/sciflow/nbs...\n",
      "2021-04-22 13:56:18.770 [1619099767342119/preprocess/2 (pid 7209)] Task finished successfully.\n",
      "2021-04-22 13:56:18.776 [1619099767342119/train/3 (pid 7221)] Task is starting.\n",
      "2021-04-22 13:56:24.787 [1619099767342119/train/3 (pid 7221)] Training /home/jovyan/git/sciflow on /home/jovyan/git/sciflow/nbs...\n",
      "2021-04-22 13:56:24.937 [1619099767342119/train/3 (pid 7221)] Task finished successfully.\n",
      "2021-04-22 13:56:24.943 [1619099767342119/last/4 (pid 7233)] Task is starting.\n",
      "2021-04-22 13:56:30.112 [1619099767342119/last/4 (pid 7233)] Task finished successfully.\n",
      "2021-04-22 13:56:30.117 [1619099767342119/end/5 (pid 7245)] Task is starting.\n",
      "2021-04-22 13:56:35.130 [1619099767342119/end/5 (pid 7245)] INFO - test_export - Running command 'track_flow'\n",
      "2021-04-22 13:56:35.133 [1619099767342119/end/5 (pid 7245)] ERROR - test_export - Failed after 0:00:00!\n",
      "2021-04-22 13:56:35.134 [1619099767342119/end/5 (pid 7245)] ERROR - test_export - Traceback (most recent call last):\n",
      "2021-04-22 13:56:35.137 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 235, in __call__\n",
      "2021-04-22 13:56:35.137 [1619099767342119/end/5 (pid 7245)]     self._emit_started()\n",
      "2021-04-22 13:56:35.137 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 333, in _emit_started\n",
      "2021-04-22 13:56:35.137 [1619099767342119/end/5 (pid 7245)]     _id=self._id,\n",
      "2021-04-22 13:56:35.137 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 194, in started_event\n",
      "2021-04-22 13:56:35.137 [1619099767342119/end/5 (pid 7245)]     _id = self._determine_run_dir(_id)\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 135, in _determine_run_dir\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)]     self.s3, self.bucket_name, s3_join(self.experiments_key_prefix, \"runs\")\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/git/text_discovery/steps/text_discovery/s3_utils.py\", line 69, in list_s3_subdirs\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)]     bucket = s3_res.Bucket(bucket_name)\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/factory.py\", line 474, in create_resource\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)]     client=self.meta.client)(*args, **kwargs)\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/base.py\", line 119, in __init__\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)]     'Required parameter {0} not set'.format(identifier))\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)] ValueError: Required parameter name not set\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)] \n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)] During handling of the above exception, another exception occurred:\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)] \n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)] Traceback (most recent call last):\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 429, in _final_call\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)]     getattr(observer, method)(**kwargs)\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 244, in failed_event\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)]     self.run_entry[\"stop_time\"] = fail_time.isoformat()\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)] TypeError: 'NoneType' object does not support item assignment\n",
      "2021-04-22 13:56:35.138 [1619099767342119/end/5 (pid 7245)] \n",
      "2021-04-22 13:56:35.139 [1619099767342119/end/5 (pid 7245)] <flow TestExportFlow step end> failed:\n",
      "2021-04-22 13:56:35.291 [1619099767342119/end/5 (pid 7245)]     Internal error\n",
      "2021-04-22 13:56:35.291 [1619099767342119/end/5 (pid 7245)] Traceback (most recent call last):\n",
      "2021-04-22 13:56:35.291 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/cli.py\", line 930, in main\n",
      "2021-04-22 13:56:35.291 [1619099767342119/end/5 (pid 7245)]     start(auto_envvar_prefix='METAFLOW', obj=state)\n",
      "2021-04-22 13:56:35.291 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 829, in __call__\n",
      "2021-04-22 13:56:35.291 [1619099767342119/end/5 (pid 7245)]     return self.main(args, kwargs)\n",
      "2021-04-22 13:56:35.291 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 782, in main\n",
      "2021-04-22 13:56:35.291 [1619099767342119/end/5 (pid 7245)]     rv = self.invoke(ctx)\n",
      "2021-04-22 13:56:35.291 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 1259, in invoke\n",
      "2021-04-22 13:56:35.291 [1619099767342119/end/5 (pid 7245)]     return _process_result(sub_ctx.command.invoke(sub_ctx))\n",
      "2021-04-22 13:56:35.291 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 1066, in invoke\n",
      "2021-04-22 13:56:35.291 [1619099767342119/end/5 (pid 7245)]     return ctx.invoke(self.callback, ctx.params)\n",
      "2021-04-22 13:56:35.291 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 610, in invoke\n",
      "2021-04-22 13:56:35.291 [1619099767342119/end/5 (pid 7245)]     return callback(args, kwargs)\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/decorators.py\", line 33, in new_func\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]     return f(get_current_context().obj, args, kwargs)\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/cli.py\", line 447, in step\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]     max_user_code_retries)\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/task.py\", line 396, in run_step\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]     self._exec_step_function(step_func)\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/task.py\", line 47, in _exec_step_function\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]     step_function()\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/git/sciflow/nbs/test/flows/test_export.py\", line 82, in end\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]     meta_info = flow_info)\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/experiment.py\", line 276, in run\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]     run()\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 235, in __call__\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]     self._emit_started()\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 333, in _emit_started\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]     _id=self._id,\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 194, in started_event\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]     _id = self._determine_run_dir(_id)\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 135, in _determine_run_dir\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]     self.s3, self.bucket_name, s3_join(self.experiments_key_prefix, \"runs\")\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/git/text_discovery/steps/text_discovery/s3_utils.py\", line 69, in list_s3_subdirs\n",
      "2021-04-22 13:56:35.292 [1619099767342119/end/5 (pid 7245)]     bucket = s3_res.Bucket(bucket_name)\n",
      "2021-04-22 13:56:35.293 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/factory.py\", line 474, in create_resource\n",
      "2021-04-22 13:56:35.293 [1619099767342119/end/5 (pid 7245)]     client=self.meta.client)(args, kwargs)\n",
      "2021-04-22 13:56:35.293 [1619099767342119/end/5 (pid 7245)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/base.py\", line 119, in __init__\n",
      "2021-04-22 13:56:35.293 [1619099767342119/end/5 (pid 7245)]     'Required parameter {0} not set'.format(identifier))\n",
      "2021-04-22 13:56:35.293 [1619099767342119/end/5 (pid 7245)] ValueError: Required parameter name not set\n",
      "2021-04-22 13:56:35.293 [1619099767342119/end/5 (pid 7245)] \n",
      "2021-04-22 13:56:35.294 [1619099767342119/end/5 (pid 7245)] Task failed.\n",
      "2021-04-22 13:56:35.294 Workflow failed.\n",
      "2021-04-22 13:56:35.294 Terminating 0 active tasks...\n",
      "2021-04-22 13:56:35.294 Flushing logs...\n",
      "    Step failure:\n",
      "    Step end (task-id 5) failed.\n"
     ]
    }
   ],
   "source": [
    "# slow\n",
    "\n",
    "check_flows(Config(cfg_name=\"test/settings.ini\"), \"--no-pylint run\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 411,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def run_flow(nb_path, params=None):\n",
    "    flow_path = get_flow_path(nb_path)\n",
    "    print(f\"Running flow: {os.path.basename(flow_path)}\")\n",
    "    ret_code, output = check_flow(\n",
    "        flow_path.parent,\n",
    "        os.path.basename(flow_path),\n",
    "        flow_command=\"--no-pylint run\",\n",
    "        params=params,\n",
    "    )\n",
    "    return ret_code, output"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 412,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Running flow: test_clustering.py\n",
      "Metaflow 2.2.7 executing TestClusteringFlow for user:e02079\n",
      "Validating your flow...\n",
      "    The graph looks good!\n",
      "2021-04-22 13:56:37.651 Workflow starting (run-id 1619099797648348):\n",
      "2021-04-22 13:56:37.658 [1619099797648348/start/1 (pid 7281)] Task is starting.\n",
      "2021-04-22 13:56:39.883 [1619099797648348/start/1 (pid 7281)] Task finished successfully.\n",
      "2021-04-22 13:56:39.890 [1619099797648348/preprocess/2 (pid 7296)] Task is starting.\n",
      "2021-04-22 13:57:08.522 [1619099797648348/preprocess/2 (pid 7296)] Task finished successfully.\n",
      "2021-04-22 13:57:08.529 [1619099797648348/fit/3 (pid 7329)] Task is starting.\n",
      "2021-04-22 13:57:10.739 [1619099797648348/fit/3 (pid 7329)] Task finished successfully.\n",
      "2021-04-22 13:57:10.746 [1619099797648348/evaluate/4 (pid 7344)] Task is starting.\n",
      "2021-04-22 13:57:12.954 [1619099797648348/evaluate/4 (pid 7344)] Task finished successfully.\n",
      "2021-04-22 13:57:12.961 [1619099797648348/end/5 (pid 7359)] Task is starting.\n",
      "2021-04-22 13:57:14.940 [1619099797648348/end/5 (pid 7359)] INFO:test_clustering:Running command 'track_flow'\n",
      "2021-04-22 13:57:14.943 [1619099797648348/end/5 (pid 7359)] ERROR:test_clustering:Failed after 0:00:00!\n",
      "2021-04-22 13:57:14.944 [1619099797648348/end/5 (pid 7359)] ERROR:test_clustering:Traceback (most recent call last):\n",
      "2021-04-22 13:57:14.948 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 235, in __call__\n",
      "2021-04-22 13:57:14.948 [1619099797648348/end/5 (pid 7359)]     self._emit_started()\n",
      "2021-04-22 13:57:14.948 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 333, in _emit_started\n",
      "2021-04-22 13:57:14.948 [1619099797648348/end/5 (pid 7359)]     _id=self._id,\n",
      "2021-04-22 13:57:14.948 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 194, in started_event\n",
      "2021-04-22 13:57:14.948 [1619099797648348/end/5 (pid 7359)]     _id = self._determine_run_dir(_id)\n",
      "2021-04-22 13:57:14.948 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 135, in _determine_run_dir\n",
      "2021-04-22 13:57:14.948 [1619099797648348/end/5 (pid 7359)]     self.s3, self.bucket_name, s3_join(self.experiments_key_prefix, \"runs\")\n",
      "2021-04-22 13:57:14.948 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/git/text_discovery/steps/text_discovery/s3_utils.py\", line 69, in list_s3_subdirs\n",
      "2021-04-22 13:57:14.948 [1619099797648348/end/5 (pid 7359)]     bucket = s3_res.Bucket(bucket_name)\n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/factory.py\", line 474, in create_resource\n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)]     client=self.meta.client)(*args, **kwargs)\n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/base.py\", line 119, in __init__\n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)]     'Required parameter {0} not set'.format(identifier))\n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)] ValueError: Required parameter name not set\n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)] \n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)] During handling of the above exception, another exception occurred:\n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)] \n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)] Traceback (most recent call last):\n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 429, in _final_call\n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)]     getattr(observer, method)(**kwargs)\n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 244, in failed_event\n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)]     self.run_entry[\"stop_time\"] = fail_time.isoformat()\n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)] TypeError: 'NoneType' object does not support item assignment\n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)] \n",
      "2021-04-22 13:57:14.949 [1619099797648348/end/5 (pid 7359)] <flow TestClusteringFlow step end> failed:\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]     Internal error\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)] Traceback (most recent call last):\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/cli.py\", line 930, in main\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]     start(auto_envvar_prefix='METAFLOW', obj=state)\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 829, in __call__\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]     return self.main(args, kwargs)\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 782, in main\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]     rv = self.invoke(ctx)\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 1259, in invoke\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]     return _process_result(sub_ctx.command.invoke(sub_ctx))\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 1066, in invoke\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]     return ctx.invoke(self.callback, ctx.params)\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/core.py\", line 610, in invoke\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]     return callback(args, kwargs)\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/click/decorators.py\", line 33, in new_func\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]     return f(get_current_context().obj, args, kwargs)\n",
      "2021-04-22 13:57:15.188 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/cli.py\", line 447, in step\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]     max_user_code_retries)\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/task.py\", line 396, in run_step\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]     self._exec_step_function(step_func)\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/metaflow/task.py\", line 47, in _exec_step_function\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]     step_function()\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/git/sciflow/nbs/test/flows/test_clustering.py\", line 90, in end\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]     meta_info = flow_info)\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/experiment.py\", line 276, in run\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]     run()\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 235, in __call__\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]     self._emit_started()\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/sacred/run.py\", line 333, in _emit_started\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]     _id=self._id,\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 194, in started_event\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]     _id = self._determine_run_dir(_id)\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/git/sciflow/sciflow/lake_observer.py\", line 135, in _determine_run_dir\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]     self.s3, self.bucket_name, s3_join(self.experiments_key_prefix, \"runs\")\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/git/text_discovery/steps/text_discovery/s3_utils.py\", line 69, in list_s3_subdirs\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]     bucket = s3_res.Bucket(bucket_name)\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/factory.py\", line 474, in create_resource\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]     client=self.meta.client)(args, kwargs)\n",
      "2021-04-22 13:57:15.189 [1619099797648348/end/5 (pid 7359)]   File \"/home/jovyan/envs/discovery/lib/python3.7/site-packages/boto3/resources/base.py\", line 119, in __init__\n",
      "2021-04-22 13:57:15.190 [1619099797648348/end/5 (pid 7359)]     'Required parameter {0} not set'.format(identifier))\n",
      "2021-04-22 13:57:15.190 [1619099797648348/end/5 (pid 7359)] ValueError: Required parameter name not set\n",
      "2021-04-22 13:57:15.190 [1619099797648348/end/5 (pid 7359)] \n",
      "2021-04-22 13:57:15.191 [1619099797648348/end/5 (pid 7359)] Task failed.\n",
      "2021-04-22 13:57:15.191 Workflow failed.\n",
      "2021-04-22 13:57:15.191 Terminating 0 active tasks...\n",
      "2021-04-22 13:57:15.191 Flushing logs...\n",
      "    Step failure:\n",
      "    Step end (task-id 5) failed.\n"
     ]
    },
    {
     "ename": "AssertionError",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAssertionError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-412-5ed1e58c6cda>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      6\u001b[0m )\n\u001b[1;32m      7\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0moutput\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 8\u001b[0;31m \u001b[0;32massert\u001b[0m \u001b[0mret_code\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;31mAssertionError\u001b[0m: "
     ]
    }
   ],
   "source": [
    "# slow\n",
    "\n",
    "ret_code, output = run_flow(\n",
    "    Path(\"/home/jovyan/git/sciflow/nbs/test/test_clustering.ipynb\"),\n",
    "    params=[(\"traffic_percent\", 10), (\"speed\", \"fast\")],\n",
    ")\n",
    "print(output)\n",
    "assert ret_code == 0"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Aynsc Flow Running\n",
    "\n",
    "> Run the flow you are working on from the notebook you are working on. This maximises the amount fo experiments you can run as you don't have down time. While long running tasks are running you can keep exploring! :-)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "async def run_flow_task(flow_path, param_grid=None):\n",
    "    experiment_id = None\n",
    "    flows_dir = flow_path.parent\n",
    "    flow_module = os.path.basename(flow_path)\n",
    "    flow_command = \"--no-pylint run\"\n",
    "    prep_mf_env()\n",
    "    if params:\n",
    "        args = \" \".join([f\"--{k} {v}\" for k, v in param_grid.items()])\n",
    "        cmd = f\"python '{os.path.join(flows_dir, flow_module)}' {flow_command} {args}\"\n",
    "    else:\n",
    "        cmd = f\"python '{os.path.join(flows_dir, flow_module)}' {flow_command}\"\n",
    "    proc = await asyncio.create_subprocess_shell(\n",
    "        cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE\n",
    "    )\n",
    "\n",
    "    stdout, stderr = await proc.communicate()\n",
    "\n",
    "    print(f\"[{cmd!r} exited with {proc.returncode}]\")\n",
    "    if stdout:\n",
    "        output = stdout.decode(\"utf-8\").strip()\n",
    "        experiment_id = [\n",
    "            s.strip('\"')\n",
    "            for s in re.search('Started run with ID \"\\d+\"', output)\n",
    "            .group(0)\n",
    "            .split(\"ID \")\n",
    "        ][1]\n",
    "        print(f\"[stdout]\\n{output}\")\n",
    "    if stderr:\n",
    "        print(f'[stderr]\\n{stderr.decode(\"utf-8\").strip()}')\n",
    "\n",
    "    return experiment_id"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def run_flow_async(nb_path, params=None):\n",
    "    flow_path = get_flow_path(nb_path)\n",
    "    loop = asyncio.get_event_loop()\n",
    "    task = loop.create_task(run_flow_task(flow_path, params))\n",
    "    task.add_done_callback(lambda x: print(f\"Task {x.result()} finished\"))\n",
    "    return task"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "task = run_flow_async(\n",
    "    os.path.join(\"test\", \"test_clustering.ipynb\"),\n",
    "    params={\"traffic_percent\": 10, \"speed\": \"fast\"},\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "task.done()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "param_grid = {\n",
    "    \"traffic_percent\": [1, 5, 10, 20, 50, 100],\n",
    "    \"speed\": [\"fast\", \"slow\"],\n",
    "    \"workers\": [1],\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def iter_param_grid(param_grid):\n",
    "    # https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/model_selection/_search.py\n",
    "    for p in [param_grid]:\n",
    "        # Always sort the keys of a dictionary, for reproducibility\n",
    "        items = sorted(p.items())\n",
    "        if not items:\n",
    "            yield {}\n",
    "        else:\n",
    "            keys, values = zip(*items)\n",
    "            for v in product(*values):\n",
    "                params = dict(zip(keys, v))\n",
    "                yield params"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "assert [{\"a\": 1, \"b\": 1, \"c\": \"hello\"}, {\"a\": 2, \"b\": 1, \"c\": \"hello\"}] == list(\n",
    "    iter_param_grid({\"a\": [1, 2], \"b\": [1], \"c\": [\"hello\"]})\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def sample_grid_space(param_grid: Dict[str, Iterable[Any]], num_samples: int):\n",
    "    samples = []\n",
    "    for i, sample in enumerate(iter_param_grid(param_grid)):\n",
    "        samples.append(sample)\n",
    "    if num_samples < len(samples):\n",
    "        samples = pd.Series(samples).sample(num_samples).tolist()\n",
    "    return samples"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "sample_space = sample_grid_space({\"a\": [1, 2], \"b\": [1], \"c\": [\"hello\"]}, 1)\n",
    "assert sample_space[0][\"b\"] == 1\n",
    "assert sample_space[0][\"c\"] == \"hello\"\n",
    "assert sample_space[0][\"a\"] == 1 or sample_space[0][\"a\"] == 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "def search_flow_grid(nb_path, param_grid, num_procs=None):\n",
    "    max_process_count = int((multiprocessing.cpu_count() / 2) - 1)\n",
    "    param_sample_space = sample_grid_space(param_grid, max_process_count)\n",
    "    tasks = []\n",
    "    for param_sample in param_sample_space:\n",
    "        tasks.append(run_flow_async(nb_path, params=param_sample))\n",
    "    return tasks"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# slow\n",
    "\n",
    "nb_path = \"/home/jovyan/git/sciflow/nbs/test/test_clustering.ipynb\"\n",
    "tasks = search_flow_grid(\n",
    "    nb_path,\n",
    "    {\n",
    "        \"traffic_percent\": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20, 30, 40, 50],\n",
    "        \"speed\": [\"fast\"],\n",
    "        \"workers\": [1],\n",
    "    },\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# slow\n",
    "\n",
    "[t.done() for t in tasks]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# slow\n",
    "\n",
    "[t.result() for t in tasks]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 413,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sciflow.lake_experiment_loader import LakeExpLoader"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 414,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ERROR IS: `ODBC error\n",
      "state: HY000\n",
      "native error code: 1040\n",
      "message: [Dremio][Connector] (1040) Dremio failed to execute the query: select * from ra_s3.sciflow.experiments.test_clustering.runs where dir0 = 51\n",
      "[30038]Query execution error. Details:[ \n",
      "VALIDATION ERROR: Table 'ra_s3.sciflow.experiments.test_clustering.runs' not found\n",
      "\n",
      "SQL Query select * from ra_s3.sciflow.experiments.test_clustering.runs where dir0 = 51\n",
      "startLine 1\n",
      "startColumn 15\n",
      "endLine 1\n",
      "endColumn 19\n",
      "\n",
      "[Error Id: 52780d00-7cf5-4464-af...[see log]`\n"
     ]
    },
    {
     "ename": "DatabaseError",
     "evalue": "ODBC error\nstate: HY000\nnative error code: 1040\nmessage: [Dremio][Connector] (1040) Dremio failed to execute the query: select * from ra_s3.sciflow.experiments.test_clustering.runs where dir0 = 51\n[30038]Query execution error. Details:[ \nVALIDATION ERROR: Table 'ra_s3.sciflow.experiments.test_clustering.runs' not found\n\nSQL Query select * from ra_s3.sciflow.experiments.test_clustering.runs where dir0 = 51\nstartLine 1\nstartColumn 15\nendLine 1\nendColumn 19\n\n[Error Id: 52780d00-7cf5-4464-af...[see log]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mError\u001b[0m                                     Traceback (most recent call last)",
      "\u001b[0;32m~/envs/discovery/lib/python3.7/site-packages/turbodbc/exceptions.py\u001b[0m in \u001b[0;36mwrapper\u001b[0;34m(*args, **kwds)\u001b[0m\n\u001b[1;32m     49\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 50\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwds\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     51\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mInternError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/envs/discovery/lib/python3.7/site-packages/turbodbc/cursor.py\u001b[0m in \u001b[0;36mexecute\u001b[0;34m(self, sql, parameters)\u001b[0m\n\u001b[1;32m    134\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_assert_valid\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 135\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mimpl\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mprepare\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msql\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    136\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mparameters\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mError\u001b[0m: ODBC error\nstate: HY000\nnative error code: 1040\nmessage: [Dremio][Connector] (1040) Dremio failed to execute the query: select * from ra_s3.sciflow.experiments.test_clustering.runs where dir0 = 51\n[30038]Query execution error. Details:[ \nVALIDATION ERROR: Table 'ra_s3.sciflow.experiments.test_clustering.runs' not found\n\nSQL Query select * from ra_s3.sciflow.experiments.test_clustering.runs where dir0 = 51\nstartLine 1\nstartColumn 15\nendLine 1\nendColumn 19\n\n[Error Id: 52780d00-7cf5-4464-af...[see log]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mDatabaseError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-414-535f3f402474>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mLakeExpLoader\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"test_clustering\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfind_by_id\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m51\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/git/sciflow/sciflow/lake_experiment_loader.py\u001b[0m in \u001b[0;36mfind_by_id\u001b[0;34m(self, experiment_id)\u001b[0m\n\u001b[1;32m     92\u001b[0m     \u001b[0;34m@\u001b[0m\u001b[0mlru_cache\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmaxsize\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mMAX_CACHE_SIZE\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     93\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mfind_by_id\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mexperiment_id\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 94\u001b[0;31m         \u001b[0mexperiments\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_find\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mexperiment_id\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mexperiment_id\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     95\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0;32mNone\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mexperiments\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m0\u001b[0m \u001b[0;32melse\u001b[0m \u001b[0mexperiments\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     96\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/git/sciflow/sciflow/lake_experiment_loader.py\u001b[0m in \u001b[0;36m_find\u001b[0;34m(self, experiment_name, experiment_ids, experiment_id, order_by, limit)\u001b[0m\n\u001b[1;32m     77\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mlimit\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     78\u001b[0m             \u001b[0mquery\u001b[0m \u001b[0;34m+=\u001b[0m \u001b[0;34mf\" limit {limit}\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 79\u001b[0;31m         \u001b[0mdata\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdremio_access\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread_sql_to_dataframe\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mquery\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     80\u001b[0m         experiments = [\n\u001b[1;32m     81\u001b[0m             LakeExperiment(\n",
      "\u001b[0;32m~/envs/discovery/lib/python3.7/site-packages/data_access/dremio_access.py\u001b[0m in \u001b[0;36mread_sql_to_dataframe\u001b[0;34m(self, sql_statement, optimise_strings, optimise_integers, use_pyodbc, date_as_object, show_ex_time, print_sql_to_log)\u001b[0m\n\u001b[1;32m    153\u001b[0m                 \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    154\u001b[0m                     dataframe = (\n\u001b[0;32m--> 155\u001b[0;31m                         \u001b[0mcursor\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mexecute\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msql_statement\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    156\u001b[0m                         .fetchallarrow(\n\u001b[1;32m    157\u001b[0m                             \u001b[0mstrings_as_dictionary\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0moptimise_strings\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/envs/discovery/lib/python3.7/site-packages/turbodbc/exceptions.py\u001b[0m in \u001b[0;36mwrapper\u001b[0;34m(*args, **kwds)\u001b[0m\n\u001b[1;32m     50\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwds\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     51\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mInternError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 52\u001b[0;31m             \u001b[0;32mraise\u001b[0m \u001b[0mDatabaseError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     53\u001b[0m         \u001b[0;32mexcept\u001b[0m \u001b[0mInternInterfaceError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     54\u001b[0m             \u001b[0;32mraise\u001b[0m \u001b[0mInterfaceError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mDatabaseError\u001b[0m: ODBC error\nstate: HY000\nnative error code: 1040\nmessage: [Dremio][Connector] (1040) Dremio failed to execute the query: select * from ra_s3.sciflow.experiments.test_clustering.runs where dir0 = 51\n[30038]Query execution error. Details:[ \nVALIDATION ERROR: Table 'ra_s3.sciflow.experiments.test_clustering.runs' not found\n\nSQL Query select * from ra_s3.sciflow.experiments.test_clustering.runs where dir0 = 51\nstartLine 1\nstartColumn 15\nendLine 1\nendColumn 19\n\n[Error Id: 52780d00-7cf5-4464-af...[see log]"
     ]
    }
   ],
   "source": [
    "LakeExpLoader(\"test_clustering\").find_by_id(51)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "@call_parse\n",
    "def sciflow_check_flows():\n",
    "    check_flows(Config())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# export\n",
    "\n",
    "\n",
    "@call_parse\n",
    "def sciflow_run_flows():\n",
    "    check_flows(Config(), \"--no-pylint run\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:jovyan-discovery]",
   "language": "python",
   "name": "conda-env-jovyan-discovery-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
